services:
  consul:
    image: consul
    container_name: consul-service
    restart: always
    ports:
      - 8500:8500
    networks:
      - micro
  jaeger:
    image: tkm/all-in-one
    container_name: jaeger-service
    restart: always
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      - micro
  fabio:
    image: fabiolb/fabio
    container_name: fabio-service
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul-service:8500
    ports:
      - 9998:9998
      - 9999:9999
    networks:
      - micro
    depends_on:
      - consul

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    environment:
      - RABBITMQ_DEFAULT_USER=joseandreshv
      - RABBITMQ_DEFAULT_PASS=Passw0rd
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - micro

networks:
  micro:
    name: micro
